name: 申请友链
description: 申请 https://blog.w1ndys.top 的友链，请先把本站加为友链
title: "申请友链: "
labels: ["友链申请"]
assignees:
  - W1ndys # 这里改成你的GitHub ID
body:
  - type: input
    id: name
    attributes:
      label: 站点名字
      placeholder: 你的站点名字
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: 站点地址
      placeholder: 站点地址
    validations:
      required: true
  - type: input
    id: word
    attributes:
      label: 站点描述
      placeholder: 这是站点描述
    validations:
      required: true
  - type: input
    id: logo
    attributes:
      label: 站点图标或个人头像
      description: 站点图标或个人头像
      placeholder: https://example.com/avatar.png
    validations:
      required: true
  - type: input
    id: group
    attributes:
      label: 友链分组
      placeholder: 大佬的聚集地
      description: 可自定义，非必填，默认为"大佬的聚集地"
