name: Hexo Deployment

on:
  workflow_dispatch: # 手动触发
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md" # 排除 README.md 等文件
      # - "**/.github/**" # 排除 .github 目录及其子目录
      - "**/LICENSE" # 排除 LICENSE 文件

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # 设置 Node.js 20.x 版本
      - name: Set up Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      # 全局安装 Hexo
      - name: Install Hexo globally
        run: |
          npm install -g hexo-cli
          npm install

      - name: Configure Git User
        run: |
          git config --global user.email "w1ndys@outlook.com"
          git config --global user.name "W1ndys"

      # 缓存 NPM 依赖
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      # 配置 SSH 密钥
      - name: Deploy to main branch
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Run Deployment
        run: hexo clean && hexo generate && hexo deploy
